ashray_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('complaint.urls',namespace='complaint')),
    url(r'^user/',include('user.urls',namespace='user')),
]

complaint/urls.py
from django.conf.urls import include, url
from .views import *
urlpatterns = [
    url(r'^$',index,name='index'),
    url(r'^dashboard/$',index,name='dashboard'),
    url(r'^update/$',update_complaint,name='update'),
]

user/urls.py
from django.conf.urls import include, url
from .views import *

urlpatterns = [
    url(r'^signin/$',user_login,name="login"),
    url(r'^signup/$',user_signup,name="signup"),
    url(r'^logout/$',user_logout,name="logout"),
]

complaint/models.py
from django.db import models
from user.models import CustUser
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=20)
    desc = models.TextField()

    def __str__(self):
        return self.name


class Complaint(models.Model):

    status_choice=(
        ("URV", "Under Review Of Volunteer"),
        ("URSC","Under Review Of State Coordinator"),
        ("URCC","Under Review Of Category Coordinator"),
        ("URA","Under Review Of Admin"),
        ("AP", "Approved"),
        ("RJ", "Rejected"),
    )

    status = models.CharField(max_length=5, choices=status_choice)
    category = models.ForeignKey(Category, blank=True, null=True)
    complaint_user = models.ForeignKey(CustUser, blank=True, null=True)
    location = models.CharField(max_length=100)
    name_child = models.CharField(max_length=25, blank=True)
    desc = models.TextField(blank=True)

    def __str__(self):
        return str(self.name_child)+" "+str(self.category)

## class PreviousWork(models.Model):

complaint/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect
from .models import *
from mapper.models import MapperNGO
from anganwadi.models import *
# Create your views here.

def index(request):

    if request.method=="POST":

        print(request.POST)

        name = request.POST['name']
        category = request.POST['category']
        desc = request.POST['desc']
        location = request.POST['location']
        category_obj = Category.objects.get(name = category)
        complaint_user = CustUser.objects.get(user=request.user)
        complaint=Complaint(complaint_user=complaint_user,name_child=name,category=category_obj,desc=desc, location=location, status="URV")

        complaint.save()

        return render(request,"complaint/complaintform.html",{"message":"Complaint registered successfully"})
    else:
        context={}
        if request.user.is_authenticated:
            cust_user = CustUser.objects.get(user = request.user)
            print (cust_user.get_user_type_display())
            if cust_user.get_user_type_display() == "Normal":
                categories = Category.objects.all()
                context = {
                    "categories": categories
                }
                return render(request, "complaint/complaintform.html", context)

            elif cust_user.get_user_type_display() == "Volunteer" :
                complaints = Complaint.objects.filter(status="URV")

            elif cust_user.get_user_type_display() == "State Coordinator" :
                complaints = Complaint.objects.filter(status="URSC")

            elif cust_user.get_user_type_display() == "Category Coordinator" :
                complaints = Complaint.objects.filter(status="URCC")

            elif cust_user.get_user_type_display() == "Category Coordinator":
                complaints = Complaint.objects.filter(status="URA")
            else:
                complaints = Complaint.objects.all()

            print(complaints)
            context = {
                "complaints": complaints,
            }
            return render(request,"complaint/dashboard.html",context)
        else:
            categories = Category.objects.all()
            context={
                "categories": categories
            }
            return render(request,"user/signup.html",context)


def update_complaint(request):

    context={}
    print("in here")
    if request.method=="POST":
        name = request.POST['name']
        value = request.POST['value']
        complaint = Complaint.objects.get(id=int(value))
        print(complaint)
        if name == "Approved-cancel" or name=="Approval-cancel":
            complaint.status = "RJ"
        else:
            status = complaint.status
            if status == "URV":
                complaint.status="URSC"
            elif status == "URSC":
                complaint.status = "URCC"
            elif status == "URCC":
                complaint_cat = complaint.category
                ngos = MapperNGO.objects.filter(category = complaint_cat)

                for ngo in ngos:
                    if ngo.ngo_name == "anganwadi":
                        transfer = AnganwadiComplaint(complaint_user = request.user.username, location = complaint.location, name_child = complaint.name_child, desc = complaint.desc, status = "PD")
                        transfer.save()

                complaint.status = "URA"
            elif status == "URA":
                complaint.status = "AP"

        complaint.save()
    return render(request,"complaint/index.html",context)

templates/complaint/base.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
    {% endblock meta %}

        <link href="{% static 'complaint/css/bootstrap.min.css' %}" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <link href="{% static 'complaint/css/index.css' %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script><!--dropdown addon-->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block pagecss %}
    {% endblock %}
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=1165100126911461";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<nav class="navbar navbar-default navbar-fixed-top" >
    <div class="container-fluid" >
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar">
                <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="/" style="color: #fff;">Ashray</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar" style="color: #000;">
            <ul class="nav navbar-nav navbar-right" style="font-weight:bold;">
                <li><a href="/" style="color: #fff;">Home</a></li>
                <li><a href="#" style="color: #fff;">Archives</a></li>
                <li><a href="#" style="color: #fff;">What we do</a></li>
                <li><a href="#" style="color: #fff;">Initiative</a></li>
                {% if request.user.is_superuser %}
                {% endif %}
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'user:login' %}" style="color: #fff;">Sign in</a></li>
                    <li><a href="{% url 'user:signup' %}" style="color: #fff;">Sign Up</a></li>
                {% else %}
                    <li class="dropdown">

                        <a class="dropdown-toggle" data-toggle="dropdown" style="color:white;" href="#">Profile
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu" style="background-color:black;color:white;">
                          <li><a href="" style="color:white;">View Profile</a></li>
                          <li><a href="" style="color:white;">Update Profile</a></li>
                          <li><a href="" style="color:white;">Create StartUp</a></li>
                          <li><a href="{% url 'user:logout' %}" style="color:white;">SignOut</a></li>
                        </ul>
                     </li>
                {% endif %}
                {% if request.user.is_superuser %}
                <li><a href=""><input type="button" class="primary" value="write a blog" /></a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
<div class="feed" style="background-color: rgba(160,160,160,1);
box-shadow: 0 0 1px rgba(0,0,0,.07);
bottom: 0;
margin-bottom: 5px;
font-size: 11px;
color: rgba(255,255,255,1);
cursor: pointer;
outline: 0;
text-align: center;
padding: 5px 10px;
position: fixed;
right: 0;
z-index: 902;">
    Feedback
</div>
<footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3>Location</h3>
                        <div id="map" class="col-md-12" style="height:300px"></div>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Around the Web</h3>
                        <ul class="list-inline">
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>About Ashray</h3>
                        <p>MBM Engineering College ,Jodhpur<a href="http://www.mbm.ac.in">ChecK Ashray</a>.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy;  team_mbm ,2017
                    </div>
                </div>
            </div>
        </div>
</footer>



<script>
function myMap() {
var mapOptions = {
    center: new google.maps.LatLng(26.268569, 73.035395),
    zoom: 17,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
}
var map = new google.maps.Map(document.getElementById("map"), mapOptions);
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAXIkDZVwrgA7zv9i3QvwxSfkWV8B-OMLo&callback=myMap"></script>
</body>

<script>
    {% block js_script %}
    {% endblock %}
</script>

</html>

templates/complaint/complaintform.html
{% extends "complaint/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
    Complaint Form
{% endblock %}

{% block content %}
<section style="min-height:100%; padding-top:50px;">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 container" style="margin-top: 100px;">
    {% if message %}
        <div class="alert alert-success alert-dismissable fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Success!</strong> {{ message }}
        </div>
    {% endif %}

  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-title text-center">
        <h1>Complaint Form</h1>
      </div>
    </div>
    <div class="panel-body">
        <form method="post">{% csrf_token %}
                <div class="form-group">
                    <b>Name of the Child*</b><input class="form-control" name="name" type="text" value="{{ x.name }}" placeholder="Name of the Child" required>
                </div>
                <div class="form-group">
                    <b>Description</b> <textarea class="form-control" name="desc" placeholder="Description" ></textarea>
                </div>
                <div class="form-group">
                    <b>Category*</b>
                    <input class="form-control" list="categories" name="category" required>
                      <datalist id="categories">
                        {% for category in categories %}
                          <option value="{{category.name}}">
                        {% endfor %}
                      </datalist>
                </div>
                <div class="form-group">
                    <b>Location*</b> <textarea class="form-control" name="location" placeholder="location" required></textarea>
                </div>
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
      {{ message }}
  </div>
</div>
</section>
{% endblock %}

templates/complaint/dashboard.html
{% extends 'complaint/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
    Dashboard
{% endblock %}

{% block content %}
<section style="min-height:75%; padding-top:50px;">
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="row" style="margin-top:100px;">
    <div class="container">
        {% if request.user.is_authenticated %}
        <div class="col-xs-3">
        <ul class="nav nav-pills nav-stacked">
                <li class="active"><a data-toggle="pill" href="#YourApproval">For Approval</a></li>
                <li><a data-toggle="pill" href="#Approved">Approved</a></li>
            </ul>
        </div>
            <div class="col-xs-9">
              <div class="tab-content">
                <div id="YourApproval" class="tab-pane fade in active">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Child Name</th>
                        <th>Category</th>
                        <th>Desc</th>
                        <th>Filed By</th>
                        <th>Location</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for complaint in complaints %}
                        <tr>
                          <td>{{ complaint.name_child }}</td>
                          <td>{{ complaint.category }}</td>
                          <td>{{ complaint.desc }}</td>
                          <td>{{ complaint.complaint_user.user.username }}</td>
                          <td>{{ complaint.location }}</td>
                          <td><button name="Approval-cancel" type="submit" id="Approval-cancel" value="{{ complaint.id }}" class="btn btn-danger">cancel</button></td>
                          <td><button name="Approval-accept" type="submit" id="Approval-accept" value="{{ complaint.id }}" class="btn btn-primary">accept</button></td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                <div id="Approved" class="tab-pane fade">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Child Name</th>
                        <th>Category</th>
                        <th>Desc</th>
                        <th>Filed By</th>
                        <th>Location</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for approve in approved %}
                      <tr>
                       <td>{{ approve.name_child }}</td>
                          <td>{{ approve.category }}</td>
                          <td>{{ approve.desc }}</td>
                          <td>{{ approve.complaint_user.user.username }}</td>
                          <td>{{ approve.location }}</td>
                        <td><button class="btn btn-danger" type="submit" value="{{approve.id}}" name="Approved-cancel">cancel</button></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
          </div>
        </div>
    </div>
            {% else %}
            <h2 class="well"> login to see dashboard </h2>
        {% endif %}
</div>
    </section>
{% endblock content %}
{% block js_script %}

$(document).ready(function(){
    $('#ApplyForm').submit(function(e){
        console.log("in log");
        e.preventDefault();
        $.ajax({
          url: "/dashboard/",
          type: "POST",
          data: $(this).serialize(),
          success : function( data ) {
              alert('Submitted');
              console.log(data);
              $('#Requestbody > tbody:last-child').append("<tr><td>"+data.start_date+"</td><td>"+data.end_date+"</td><td>"+data.type+"</td><td><span class='label label-danger'>PD</span></td><td><button name='Request-cancel' type='submit' value="+ data.id +" class='btn btn-danger'>cancel</button></td></tr>");
                console.log("Success");
            },
            error   : function( xhr, err ) {
                         console.log(xhr+ 'Error'+ err);
            }
        });
    });


    $('button').click(function(e){
        console.log("in button");
        e.preventDefault();
        $.ajax({
          url: "/update/",
          type: 'POST',
          data: {
            name :$(this).attr('name'),
            value: $(this).attr('value'),
            csrfmiddlewaretoken: '{{ csrf_token }}',
          },
          success : function( data ) {
              alert('ok');
            },
            error   : function( xhr, err ) {
                         alert('Error');
            }
        });
        $(this).closest('tr').hide();
    });

});



{% endblock js_script  %}

templates/complaint/index.html
{% extends 'complaint/base.html' %}

{% block content %}

{% endblock %}